### ISSUE TITLE
DeepSpeech2 코드 이해

### ISSUE THREAD

**Issue by MrSteveChoi** [GoX2Maker/ConnectsLab_Speech#2]
## Description
- DeepSpeech2 코드를 end-2-end로 이해한다. 

## Tasks
- [ ] DeepSpeech2 코드 이해하기. (희영)
- [ ] DeepSpeech2 코드 이해하기. (선민)
- [ ] DeepSpeech2 코드 이해하기. (인철)
- [ ] DeepSpeech2 코드 이해하기. (민주)
- [ ] DeepSpeech2 코드 이해하기. (민수)
